version: "3.8"

services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  # app:
  #   links:
  #     - db:db
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   image: node:18
  #   ports:
  #     - "3000:3000"
  #   command: npm run build:start
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   env_file:
  #     - .env

volumes:
  postgres_data_volume:
    driver: local
